---

- name: Provision the webserver tier
  ### hosts is a list of all hosts this would apply to .. can be a named host
  # hosts: SANDBOX-LOCAL
  ### OR it can be a list of hosts stored in the inventory/hosts file
  hosts: webservers
  sudo: yes
  remote_user: admin
  roles:
    - webserver
