---
- name: ensure port 80 is open on firewalld
  command: firewall-cmd --permanent --add-service http
- name: ensure apache is at the latest version
  yum: pkg=httpd state=latest
#- name: write the apache config file
#  template: src=/srv/httpd.j2 dest=/etc/httpd/conf.d/httpd.conf
#  notify:
#  - restart apache
- name: ensure apache is running
  service: name=httpd state=started
